controller_list:
  - name: fake_right_arm_group_controller
    joints:
      - right_upper_arm_to_right_shoulder
      - right_elbow_joint
  - name: fake_left_arm_group_controller
    joints:
      - kneeling_joint
      - bowing_joint
      - left_shoulder_to_body
      - left_upper_arm_to_left_shoulder
      - left_elbow_joint
  - name: fake_right_arm_w_body_controller
    joints:
      - kneeling_joint
      - bowing_joint
      - right_shoulder_to_body
      - right_upper_arm_to_right_shoulder
      - right_elbow_joint
initial:  # Define initial robot poses.
  - group: right_arm_group
    pose: Home
  - group: left_arm_group
    pose: Home