# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm_group
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - kneeling_joint
    - bowing_joint
    - left_shoulder_to_body
    - left_upper_arm_to_left_shoulder
    - left_elbow_joint
    - right_shoulder_to_body
    - right_upper_arm_to_right_shoulder
    - right_elbow_joint
    - left_wheel_to_base
    - right_wheel_to_base
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
    - name: oskar3_left_hand_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - left_shoulder_to_body
        - left_upper_arm_to_left_shoulder
        - left_elbow_joint
        - bowing_joint
        - kneeling_joint
